# Generated by Django 4.1.7 on 2023-03-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacao_generica', models.CharField(max_length=222)),
                ('concentracao_composicao', models.CharField(max_length=222)),
                ('forma_farmaceutica', models.CharField(max_length=222)),
                ('codigo_atc', models.CharField(max_length=222)),
                ('componente', models.CharField(max_length=222)),
            ],
        ),
    ]
